### ISSUE TITLE
Chart is not working

### ISSUE THREAD

**Issue by ankitojha07** [ankittojha/covid19-tracker#1]
In src App.js : Line no. 36 is commented.

-> Remove that comment and run this project on local server. 
-> Open console tab in browser -> you will see an error.
-> Solve that error and make a PR.

File location : sec > components > Chart > ChartShow.jsx

**Comment by foobar41** [comment]
Hey, I'd like to try this

**Comment by satyagalla** [comment]
Hey, I'd like to try this

**Comment by ankittojha** [comment]
sure

**Comment by ankitojha07** [comment]
> Hey, I'd like to try this

sure

**Comment by MarinJursic** [comment]
Add this to your imports

`import 'chart.js/auto'`

If you don't have the chart.js package installed:

`npm i chart.js`

**Comment by satyagalla** [comment]
This seems to be working, thank you

**Comment by ankitojha07** [comment]
> Add this to your imports
> 
> `import 'chart.js/auto'`
> 
> If you don't have the chart.js package installed:
> 
> `npm i chart.js`

Thank you so much

**Comment by ankitojha07** [comment]
Solved
